// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etmmechziwyyebzqhcvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0bW1lY2h6aXd5eWVienFoY3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MzE4MTQsImV4cCI6MjA2MjUwNzgxNH0.ScJfPJDNHMmkqf7Ghq7meKR37RYeqyU9h8Wjt--0ZNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);